### ISSUE TITLE
Issue using opsgenie-go-sdk with URL parameters.

### ISSUE THREAD

**Issue by sciffer** [opsgenie/opsgenie-go-sdk#5]
The SDK uses a function to translate the request struct to URL Parameters, but those parameters are not aligned with the caps that the API requires.
For example the url parameter apiKey will become APIKey(which is based on the naming of the struct and not the naming of the JSON) - the result for that will be a request cannot have an empty apiKey value.

**Comment by tubaozturk** [comment]
On get and delete requests, you need to use **url** key instead of **json**. Because those parameters should be added to url instead of json content.
APIKey field should be like the example below for get and delete requests:
`APIKey string`url:"apiKey,omitempty"`` 

I made the fixes on requests and client objects before merging your pull request. It works as expected now.
